services:
  postgres:
    image: postgres:15
    container_name: hirely_postgres
    environment:  
      POSTGRES_DB: hirely_db
      POSTGRES_USER: hirely_user
      POSTGRES_PASSWORD: 1122
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hirely_user -d hirely_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hirely_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hirely_backend
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - backend_static:/app/HirelyBackend/staticfiles
    networks:
      - hirely_network
    restart: unless-stopped

  frontend:
    build:
      context: ./hirely-frontend
      dockerfile: Dockerfile
      args:
        - GOOGLE_GENERATIVE_API_KEY=${GOOGLE_GENERATIVE_API_KEY}
        - NEXT_PUBLIC_VAPI_WEB_TOKEN=${NEXT_PUBLIC_VAPI_WEB_TOKEN}
        - NEXT_PUBLIC_VAPI_WORKFLOW_ID=${NEXT_PUBLIC_VAPI_WORKFLOW_ID}
        - DATABASE_URL=${DATABASE_URL}
    container_name: hirely_frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - DJANGO_BASE_URL=http://backend:8000
      - GOOGLE_GENERATIVE_API_KEY=${GOOGLE_GENERATIVE_API_KEY}
      - NEXT_PUBLIC_VAPI_WEB_TOKEN=${NEXT_PUBLIC_VAPI_WEB_TOKEN}
      - NEXT_PUBLIC_VAPI_WORKFLOW_ID=${NEXT_PUBLIC_VAPI_WORKFLOW_ID}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - hirely_network
    restart: unless-stopped

volumes:
  postgres_data:
  backend_static:

networks:
  hirely_network:
    driver: bridge




    